# Generated by Django 2.2.4 on 2019-08-06 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('custom_profile', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='user',
        ),
        migrations.AddField(
            model_name='profile',
            name='school_class',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='custom_profile.Class'),
        ),
    ]
