# Generated by Django 2.2.4 on 2019-08-06 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('custom_profile', '0002_auto_20190806_0639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='school_class',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='custom_profile.Class'),
        ),
    ]
