# Generated by Django 2.2.4 on 2019-08-06 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_profile', '0003_auto_20190806_0711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='school_class',
            field=models.CharField(max_length=50),
        ),
    ]
