# Generated by Django 2.2.4 on 2019-08-06 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_profile', '0004_auto_20190806_0741'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='school_class',
        ),
    ]
