# Generated by Django 2.2.4 on 2019-08-06 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_profile', '0005_remove_profile_school_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='student_id',
            field=models.CharField(default='-1', max_length=50),
        ),
    ]
